# Generated by Django 3.1.7 on 2021-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller')], default='B', max_length=1),
        ),
    ]
