# Generated by Django 3.1.7 on 2021-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
