# Generated by Django 3.1.7 on 2021-06-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='locality',
        ),
    ]
