# Generated by Django 3.1.7 on 2021-04-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210428_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_creator', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
