# Generated by Django 3.1.7 on 2021-04-23 01:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('image_url', models.CharField(max_length=255, verbose_name='Images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Timestamp Updated')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('content', models.TextField(verbose_name='Content')),
                ('image_url', models.CharField(max_length=255, verbose_name='Images')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Timestamp Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreview_review_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreview_review_product', to='store.product', verbose_name='Product')),
            ],
        ),
    ]
