# Generated by Django 3.1.7 on 2021-04-28 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20210428_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_creator', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_image',
            field=models.ImageField(upload_to=store.models.review_image_path),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
